name: ❓ Question
description: Ask a question about setup, usage, or anything else
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        No dumb questions. Ask away.

  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "What do you want to know?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: "What are you trying to do? What have you tried?"
